### ISSUE TITLE
Can you make it work on the Steamdb site as well ?

### ISSUE THREAD

**Issue by DogancanYr** [solidet-com/steam-currency-converter#5]

**Comment by DogancanYr** [comment]
😞😞

**Comment by Trsnaqe** [comment]
Apologies 😬 We considered it but couldn’t find a feasible way to parse only prices on SteamDB. However, if someone can suggest a viable method to achieve this, I’d be happy to extend or develop a new solution to support SteamDB. Sorry for the inconvenience. Üzgünüm 😞
