### ISSUE TITLE
Incompatible with stupid steam pricing (18.--€)

### ISSUE THREAD

**Issue by UwQ-Official** [solidet-com/steam-currency-converter#9]
The current price of [BeamNG.drive](https://store.steampowered.com/app/284160/BeamNGdrive/) is 18.--€ (18.00€), meaning the extension doesn't convert it as its not a number value

**Comment by Trsnaqe** [comment]
Hey!

Thank you for bringing this to our attention. I will update the extension tomorrow to address this issue and #8.
